# Jekyll configuration for GitHub Pages
title: Foundry VTT Module Documentation
description: Documentation for Foundry VTT modules including Journeys & Jamborees and ARGON Dragonbane
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://docs.rayners.dev" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
theme: minima

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Custom domain for GitHub Pages
# This will be configured in the repository settings